config/routes.rb
Rails.application.routes.draw do
 
  root 'students#index'
  resources :students
  resources :enrollments, only: [:new, :create, :destroy]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :enrollments
	has_many :students,through: :enrollments
	
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :student
	belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :enrollments
	has_many :courses, through: :enrollments
	validates :name, presence: true
	validates :name,uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def index
  end

  def new
    @enrollment = Enrollment.new
  end

  def create
    @enrollment = Enrollment.create(params.require(:enrollment).permit(:courese_id, :student_id))
    redirect_to student_path(@enrollment.student)
  end

  def destroy
    #byebug
    @enrollment = Enrollment.find(params[:id])
    @student = @enrollment.student
    @enrollment.destroy
    redirect_to student_path(@student)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student=Student.new
  end

  def create
    @student=Student.create(params.require(:student).permit(:name, :age))
    if @student.valid?
      redirect_to students_path
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to new_student_path
    end
  end

  def show
    @student =Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    #byebug
    @student = Student.find(params[:id])
    @student.update(params.require(:student).permit(:name, :age))
    redirect_to student_path(@student)
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>

app/views/enrollments/create.html.erb
<h1>Enrollments#create</h1>
<p>Find me in app/views/enrollments/create.html.erb</p>

app/views/enrollments/destroy.html.erb
<h1>Enrollments#destroy</h1>
<p>Find me in app/views/enrollments/destroy.html.erb</p>

app/views/enrollments/index.html.erb
<h1>Enrollments#index</h1>
<p>Find me in app/views/enrollments/index.html.erb</p>

app/views/enrollments/new.html.erb
<h1> Register for New Course </h1>
<%= form_for @enrollment do |f|%>
   <%= f.label :course_id%>
   <%= f.collection_select :course_id, Course.all, :id, :name%>
   <%= f.label :student_id %>
   <%= f.collection_select :student_id, Student.all,:id, :name%>
   <%= f.submit%>
<%end%>

app/views/enrollments/show.html.erb
<h1> Register for New Course </h1>
<%= form_for @enrollment do |f|%>
   <%=f.label :course_id %>
    <%= f.collection_select :course_id, Course.all, :id, :name %>
    <%= f.label :students_id %>
     <%= f.collection_select :student_id, Student.all,:id,:name%>
       <%=f.submit%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseRegApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Students Index</h1>

<%= button_to "Add New Student", new_student_path, method: :get %>
<ul>
<% @students.each do |student|%>
    <li><%= link_to student.name, student_path(student)%> </li>
    <%end%>
    </ul>

app/views/students/new.html.erb
<h1>Students New Form</h1>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
       <p style="color: red"> <%= error%></p>
    <%end%>
<%end%>
<%=form_for @student do |f|%>
        <%= f.label :name%>
        <%= f.text_field :name %>
        <%=f.label :age%>
        <%= f.number_field :age%>

        <%= f.submit%>
<%end%>

app/views/students/show.html.erb
<h1><%= @student.name%>'S Page</h1>
<h2>Age: <%=@student.age%></h2>
<h2> Courses </h2>
<%= button_to "Register Course", new_enrollment_path, method: :get%>
<ul>
    <%@student.enrollments.each do |enrollment|%>
         <li><%= enrollment.course.name%></li>
          <%= button_to "Drop Enrollment", enrollment_path(enrollment), method: :delete%>
    <%end%>
</ul>
<%= button_to "Edit Student", edit_student_path, method: :get%>
<%= button_to "Destroy Student", student_path, method: :delete%>


<%= link_to "Destroy Student", student_path%>
 

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>